name: Deploy action for NextJs

on:
  workflow_dispatch:
    inputs:
      deploy_note:
        description: 'Write down your note for this deploy version'
        required: true
        default: 'Deploy to staging Client'
      deploy_branch:
        description: 'Type branch name'
        required: true
        default: 'main'

jobs:
  nextjs-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install --force
          npm run build

  # Auto deploy to Staging server
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: nextjs-ci
    steps:
      - name: Deploy Web Stg
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd PhoneType/PhoneTypeClient
            git fetch origin ${{ github.event.inputs.deploy_branch }}
            git checkout -f
            git checkout ${{ github.event.inputs.deploy_branch }}
            git pull origin ${{ github.event.inputs.deploy_branch }}
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads npm
            export NODE_OPTIONS=--max_old_space_size=4096
            npm install --force
            npm run build
            pm2 reload ecosystem.config.js
